apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ng-dep
spec:
  replicas: 2
  template:
    metadata:
      name: ng-pod
      labels:
        target: dev
    spec:
      containers:
      - name: nginx
        image: k8slab/nginx:1.0
        ports:
        - containerPort: 80
          protocol: TCP
