apiVersion: v1
kind: Pod
metadata:
  name: high-priority-3
spec:
  containers:
  - name: high-priority
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "200Gi"
        cpu: "1k"
      limits:
        memory: "200Gi"
        cpu: "1k"
  priorityClassName: high-priority