apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: my-data-store2
spec:
 accessModes:
 - ReadWriteOnce
 storageClassName: default
 resources:
  requests:
   storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
 name: mypod2
spec:
 volumes:
  - name: my-volume
    persistentVolumeClaim:
     claimName: my-data-store2
 containers:
 - image: nginx:1.15.5
   name: mypod
   volumeMounts:
   - name: my-volume
     mountPath: /mnt/mydemo